package receiverhttp

import (
	"bufio"
	"context"
	"errors"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/ooarchitect92/greeto_ananta/backend/services/webhook-dispatcher/receiving"
)

// These servers exist ONLY for local wire tests. No runtime listener is shipped.
// TLS certificates are generated by net/http/httptest and trusted only by its client.
func server(t *testing.T, h http.Handler, tls bool) *httptest.Server {
	t.Helper()
	s := httptest.NewUnstartedServer(h)
	s.Config.ReadHeaderTimeout = time.Second
	s.Config.IdleTimeout = time.Second
	s.Config.MaxHeaderBytes = 8192
	if tls {
		s.StartTLS()
	} else {
		s.Start()
	}
	t.Cleanup(s.Close)
	s.Client().Timeout = 3 * time.Second
	return s
}
func send(t *testing.T, s *httptest.Server) *http.Response {
	t.Helper()
	r := request(t, payload())
	r.URL.Scheme = strings.Split(s.URL, ":")[0]
	r.URL.Host = strings.TrimPrefix(s.URL, r.URL.Scheme+"://")
	r.Host = r.URL.Host
	r.RequestURI = ""
	response, err := s.Client().Do(r)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { response.Body.Close() })
	return response
}
func TestTLSResponseWaitsForMatchingCommit(t *testing.T) {
	k, g, _ := ports()
	entered, release := make(chan struct{}), make(chan struct{})
	var once sync.Once
	defer once.Do(func() { close(release) })
	i := inboxFunc(func(ctx context.Context, id Identity, _ receiving.Event) (Receipt, error) {
		close(entered)
		select {
		case <-release:
			return Receipt{id, "receipt-fixture", "accepted"}, nil
		case <-ctx.Done():
			return Receipt{}, ctx.Err()
		}
	})
	h := mustHandler(t, k, g, i, config())
	s := server(t, h, true)
	result := make(chan int, 1)
	go func() {
		r := request(t, payload())
		r.URL.Scheme = "https"
		r.URL.Host = strings.TrimPrefix(s.URL, "https://")
		r.Host = r.URL.Host
		r.RequestURI = ""
		resp, err := s.Client().Do(r)
		if err != nil {
			result <- 0
			return
		}
		defer resp.Body.Close()
		result <- resp.StatusCode
	}()
	select {
	case <-entered:
	case <-time.After(2 * time.Second):
		t.Fatal("inbox was never called")
	}
	select {
	case code := <-result:
		t.Fatalf("response %d before commit acknowledgement", code)
	case <-time.After(30 * time.Millisecond):
	}
	once.Do(func() { close(release) })
	select {
	case code := <-result:
		if code != 204 {
			t.Fatal(code)
		}
	case <-time.After(2 * time.Second):
		t.Fatal("no response after commit")
	}
}
func TestTLSLostACKAndDuplicate(t *testing.T) {
	k, g, _ := ports()
	inbox := &fakeInbox{receipts: map[string]Receipt{}, loseOnce: true}
	h := mustHandler(t, k, g, inbox, config())
	s := server(t, h, true)
	if r := send(t, s); r.StatusCode != 503 {
		t.Fatal("lost ACK should not succeed")
	}
	if r := send(t, s); r.StatusCode != 204 {
		t.Fatal("retry should recover receipt")
	}
	if r := send(t, s); r.StatusCode != 204 {
		t.Fatal("duplicate should retain receipt")
	}
	inbox.mu.Lock()
	count := inbox.effects
	inbox.mu.Unlock()
	if count != 1 {
		t.Fatal("duplicated local effect")
	}
}
func TestTLSConcurrentDuplicates(t *testing.T) {
	k, g, _ := ports()
	f := &fakeInbox{receipts: map[string]Receipt{}}
	h := mustHandler(t, k, g, f, config())
	s := server(t, h, true)
	var wg sync.WaitGroup
	for n := 0; n < 8; n++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			r := request(t, payload())
			r.URL.Scheme = "https"
			r.URL.Host = strings.TrimPrefix(s.URL, "https://")
			r.Host = r.URL.Host
			r.RequestURI = ""
			resp, err := s.Client().Do(r)
			if err != nil {
				t.Error(err)
				return
			}
			defer resp.Body.Close()
			if resp.StatusCode != 204 {
				t.Error(resp.StatusCode)
			}
		}()
	}
	wg.Wait()
	f.mu.Lock()
	defer f.mu.Unlock()
	if f.effects != 1 {
		t.Fatal("concurrent duplicate effect")
	}
}
func TestBoundedAdmissionAndDrain(t *testing.T) {
	k, g, _ := ports()
	entered, release := make(chan struct{}), make(chan struct{})
	var once sync.Once
	defer once.Do(func() { close(release) })
	i := inboxFunc(func(ctx context.Context, id Identity, _ receiving.Event) (Receipt, error) {
		close(entered)
		select {
		case <-release:
			return Receipt{id, "r", "accepted"}, nil
		case <-ctx.Done():
			return Receipt{}, ctx.Err()
		}
	})
	c := config()
	c.MaxConcurrent = 1
	h := mustHandler(t, k, g, i, c)
	done := make(chan struct{})
	go func() { defer close(done); call(t, h, request(t, payload()), newWriter(), 204) }()
	select {
	case <-entered:
	case <-time.After(time.Second):
		t.Fatal("no admission")
	}
	call(t, h, request(t, payload()), newWriter(), 503)
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
	defer cancel()
	if err := h.Drain(ctx); !errors.Is(err, context.DeadlineExceeded) {
		t.Fatal("drain should time out, not cancel commit", err)
	}
	call(t, h, request(t, payload()), newWriter(), 503)
	once.Do(func() { close(release) })
	select {
	case <-done:
	case <-time.After(time.Second):
		t.Fatal("inflight commit did not finish")
	}
	wait, stop := context.WithTimeout(context.Background(), time.Second)
	defer stop()
	if h.Drain(wait) != nil {
		t.Fatal("drain failed")
	}
	call(t, h, request(t, payload()), newWriter(), 503)
}
func TestDrainWaitsForFinalResponse(t *testing.T) {
	k, g, i := ports()
	h := mustHandler(t, k, g, i, config())
	entered, release := make(chan struct{}), make(chan struct{})
	var once sync.Once
	defer once.Do(func() { close(release) })
	w := &blockingWriter{writer: newWriter(), entered: entered, release: release}
	done := make(chan struct{})
	go func() { h.ServeHTTP(w, request(t, payload())); close(done) }()
	<-entered
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
	defer cancel()
	if !errors.Is(h.Drain(ctx), context.DeadlineExceeded) {
		t.Fatal("drain returned before response")
	}
	once.Do(func() { close(release) })
	select {
	case <-done:
	case <-time.After(time.Second):
		t.Fatal("final response did not finish")
	}
}

type blockingWriter struct {
	*writer
	entered chan struct{}
	release chan struct{}
}

func (w *blockingWriter) WriteHeader(code int) {
	close(w.entered)
	<-w.release
	w.writer.WriteHeader(code)
}

func TestSlowBodyHasNoSuccess(t *testing.T) {
	k, g, _ := ports()
	c := config()
	c.Timeout = 150 * time.Millisecond
	calls := 0
	i := inboxFunc(func(context.Context, Identity, receiving.Event) (Receipt, error) { calls++; return Receipt{}, nil })
	h := mustHandler(t, k, g, i, c)
	finished := make(chan struct{})
	s := server(t, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) { defer close(finished); h.ServeHTTP(w, r) }), false)
	conn, err := net.DialTimeout("tcp", strings.TrimPrefix(s.URL, "http://"), time.Second)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	_ = conn.SetDeadline(time.Now().Add(2 * time.Second))
	_, err = io.WriteString(conn, "POST /callback HTTP/1.1\r\nHost: fixture\r\nContent-Type: application/json\r\nContent-Length: 900\r\n\r\n{")
	if err != nil {
		t.Fatal(err)
	}
	resp, err := http.ReadResponse(bufio.NewReader(conn), nil)
	if err == nil {
		defer resp.Body.Close()
		if resp.StatusCode >= 200 && resp.StatusCode < 300 {
			t.Fatal("partial body acknowledged")
		}
	}
	// The original write deadline may yield EOF rather than an error response.
	// Either is non-success; no durability port may have received partial bytes.
	select {
	case <-finished:
	case <-time.After(time.Second):
		t.Fatal("slow request handler did not finish")
	}
	h.mu.Lock()
	active := h.active
	h.mu.Unlock()
	if active != 0 {
		t.Fatal("handler did not release bounded attempt")
	}
	if calls != 0 {
		t.Fatal("partial request reached inbox")
	}
}
func TestChunkedAndIdentityEncoding(t *testing.T) {
	k, g, i := ports()
	h := mustHandler(t, k, g, i, config())
	s := server(t, h, true)
	r := request(t, payload())
	r.URL.Scheme = "https"
	r.URL.Host = strings.TrimPrefix(s.URL, "https://")
	r.Host = r.URL.Host
	r.RequestURI = ""
	r.ContentLength = -1
	r.Header.Set("Content-Encoding", "identity")
	r.Header.Set("Content-Type", "application/json; charset=UTF-8")
	resp, err := s.Client().Do(r)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 204 {
		t.Fatal(resp.StatusCode)
	}
}
