import { useState } from 'react';
import { CheckCircle2, Lock, UserRound } from 'lucide-react';
import { acceptWorkspaceInvite } from './api.js';
import { AuthNotice } from './VerifyEmailPage.jsx';

export default function InviteAcceptancePage() {
  const token = new URLSearchParams(window.location.search).get('token') || '';
  const [name, setName] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); if (!token) return setError('This invite link is missing its token.'); if (password !== confirm) return setError('Passwords do not match.'); setLoading(true); try { const response = await acceptWorkspaceInvite({ token, name, password }); if (!response.success) setError(response.message || 'This invite is no longer valid.'); else setDone(true); } catch (err) { setError(err?.message || 'This invite is no longer valid.'); } finally { setLoading(false); } };
  if (done) return <AuthNotice icon={<CheckCircle2 size={40} className="text-emerald-500" />} title="Workspace invite accepted" message="Your account is ready. Sign in to join your team." action={{ href: '/login', label: 'Sign in' }} />;
  return <main className="flex min-h-screen items-center justify-center bg-[#f6f4fb] p-5"><section className="w-full max-w-md border border-violet-100 bg-white p-8 shadow-[0_24px_70px_rgba(51,25,100,0.12)]"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-violet-600">Greeto workspace invite</p><h1 className="mt-3 text-2xl font-semibold text-slate-950">Join your team</h1><p className="mt-2 text-sm leading-6 text-slate-600">Set your name and password to accept this workspace invitation.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-xs font-semibold text-slate-700">Name<span className="mt-1.5 flex h-11 items-center border border-slate-200 px-3"><UserRound size={16} className="mr-2 text-slate-400"/><input required value={name} onChange={(e) => setName(e.target.value)} className="w-full outline-none" /></span></label><label className="block text-xs font-semibold text-slate-700">Password<span className="mt-1.5 flex h-11 items-center border border-slate-200 px-3"><Lock size={16} className="mr-2 text-slate-400"/><input type="password" required minLength="8" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full outline-none" /></span></label><label className="block text-xs font-semibold text-slate-700">Confirm password<input type="password" required minLength="8" value={confirm} onChange={(e) => setConfirm(e.target.value)} className="mt-1.5 h-11 w-full border border-slate-200 px-3 outline-none" /></label>{error && <p className="border border-red-200 bg-red-50 p-2 text-sm text-red-700">{error}</p>}<button disabled={loading} className="h-11 w-full bg-[#6d3df5] text-sm font-semibold text-white hover:bg-[#5830d4] disabled:opacity-60">{loading ? 'Accepting invite...' : 'Accept invite'}</button></form></section></main>;
}
