import React, {useEffect,useMemo,useState} from 'react';
import { groups, getFeature } from '../../app/navigation/registry.js';
import features from '../../contracts/features.json';
import workPackages from '../../contracts/work-packages.json';
import apiInventory from '../../contracts/legacy-api-inventory.json';
import { PageLayout, Notice, downloadJson } from '../../shared/ui/PageLayout.jsx';
import ProductionReadinessPanel from './ProductionReadinessPanel.jsx';
import TenantScopePanel from './TenantScopePanel.jsx';
import deliveryStatus from '../../contracts/delivery-status.json';
import { selectedTask } from '../../app/navigation/policy.js';
// Overlay source-evidenced progress without mutating the immutable baseline records.
const progressById = new Map(deliveryStatus.items.map(item => [item.id,item]));
/**
 * @param {object} props Existing workspace navigation dependencies.
 * @param {Function} props.onNavigate Opens a registered feature through the shell.
 * @returns {React.ReactElement} Baseline requirements with separate current evidence.
 * Side effects are browser navigation and local exports only; this view cannot
 * certify acceptance, approve a pipeline change or start production deployment.
 */
export default function ImplementationCenter({onNavigate}) {
  const [view,setView]=useState('packages'),[query,setQuery]=useState(''),[domain,setDomain]=useState(''),[gate,setGate]=useState(''),[priority,setPriority]=useState('');
  const [selected,setSelected]=useState(()=>selectedTask(window.location.search,workPackages));
  useEffect(()=>{const update=()=>setSelected(selectedTask(window.location.search,workPackages));window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[]);
  const domains=useMemo(()=>[...new Set(workPackages.map(t=>t.domain))].sort(),[]);
  const results=workPackages.filter(task=>(!domain||task.domain===domain)&&(!gate||task.gate===gate)&&(!priority||task.priority===priority)&&`${task.id} ${task.name} ${task.domain} ${task.acceptance}`.toLowerCase().includes(query.toLowerCase()));
  const showTask=task=>{setSelected(task);const url=new URL(window.location.href);url.searchParams.set('task',task.id);window.history.pushState(null,'',url.pathname+url.search);document.getElementById('work-package-detail')?.focus();};
  return <PageLayout eyebrow="Delivery / Traceability" title="Implementation center" description="A source-linked workbench for building the platform one feature at a time."
    actions={<button type="button" className="greeto-button" onClick={()=>downloadJson(workPackages,'greeto-work-package-map.json')}>Export work-package map</button>}>
    <div className="greeto-stat-grid"><div className="greeto-stat"><span>Registered feature pages</span><strong>{features.length}</strong><small>Existing screens + frontend configuration</small></div><div className="greeto-stat"><span>Source work packages</span><strong>{workPackages.length}</strong><small>{domains.length} domains · Exact original IDs</small></div><div className="greeto-stat"><span>Documented parameters</span><strong>{features.reduce((n,f)=>n+f.fields.length,0)}</strong><small>Browser configuration contracts</small></div><div className="greeto-stat"><span>Work packages certified here</span><strong>{deliveryStatus.certified_done}</strong><small>Completion requires acceptance evidence</small></div></div>
    <Notice>All {workPackages.length} baseline records are preserved. The table overlays the latest repository status; original status remains in the detail view. A page, field or dependency link does not complete a work package. No backend, provider approval, billing operation or production scale claim is certified here.</Notice>
    <div className="greeto-tabs" aria-label="Implementation views">{[['packages','Work packages'],['features','Feature map'],['api','Existing API inventory'],['readiness','Readiness & evidence']].map(([id,label])=><button type="button" key={id} aria-pressed={view===id} onClick={()=>{setView(id);setQuery('');}}>{label}</button>)}</div>
    {view!=='readiness' && <div className="greeto-card greeto-filter-bar"><label><span>Search {view==='packages'?'IDs and requirements':view==='features'?'features':'function names and parameters'}</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==='packages'?'MIS-001, consent, workflows…':'Search…'}/></label>
      {view==='packages'&&<><label><span>Domain</span><select value={domain} onChange={e=>setDomain(e.target.value)}><option value="">All domains</option>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label><span>Gate</span><select value={gate} onChange={e=>setGate(e.target.value)}><option value="">All gates</option>{[...new Set(workPackages.map(t=>t.gate))].sort().map(g=><option key={g}>{g}</option>)}</select></label><label><span>Priority</span><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">All priorities</option>{[...new Set(workPackages.map(t=>t.priority))].sort().map(p=><option key={p}>{p}</option>)}</select></label><button className="greeto-button" type="button" onClick={()=>{setQuery('');setDomain('');setGate('');setPriority('');}}>Clear filters</button></>}
    </div>}
    {view==='readiness' && <><ProductionReadinessPanel/><TenantScopePanel/></>}
    {view==='packages'&&<><div className="greeto-card"><div className="greeto-card-heading"><h2>Source work packages</h2><p role="status">{results.length} of {workPackages.length} shown</p></div><div className="greeto-table-wrap"><table><thead><tr><th>ID / domain</th><th>Feature / work package</th><th>Gate</th><th>Owner</th><th>Delivery status</th></tr></thead><tbody>{results.map(task=><tr key={task.id} className={selected?.id===task.id?'is-selected':''}><td><button type="button" className="greeto-text-link" onClick={()=>showTask(task)}>{task.id}</button><small>{task.domain}</small></td><td><button type="button" className="greeto-table-link" onClick={()=>showTask(task)}>{task.name}</button><small>{getFeature(task.frontendFeature)?.label}</small></td><td>{task.gate}<small>{task.priority}</small></td><td>{task.squad}<small>{task.assignee}</small></td><td><span className="greeto-badge muted">{progressById.get(task.id)?.status || task.baselineStatus}</span></td></tr>)}</tbody></table>{!results.length&&<p className="greeto-empty">No work packages match these filters.</p>}</div></div>
      <article className="greeto-card greeto-detail-panel" id="work-package-detail" tabIndex={-1} aria-label="Work package detail">{selected?<><p className="greeto-eyebrow">{selected.id} / {selected.domain}</p><h2>{selected.name}</h2><p>{selected.acceptance}</p><dl className="greeto-details"><dt>Acceptance test</dt><dd><code>{selected.acceptanceTestId}</code></dd><dt>Baseline status</dt><dd>{selected.baselineStatus} · Original source snapshot</dd><dt>Current delivery status</dt><dd>{progressById.get(selected.id)?.status || selected.baselineStatus}</dd><dt>Source contribution</dt><dd>{progressById.get(selected.id)?.contribution || 'No contribution recorded in this increment.'}</dd><dt>Remaining acceptance</dt><dd>{progressById.get(selected.id)?.remaining || 'Original prerequisites and acceptance criteria still apply.'}</dd><dt>Evidence commit</dt><dd><code>{deliveryStatus.evidence_commit || 'Remote publication not yet recorded'}</code> · Source evidence, not production certification</dd><dt>Source</dt><dd>{selected.source} · Row {selected.sourceRow}</dd><dt>Frontend entry</dt><dd><code>{selected.frontendPath}</code></dd><dt>Proposed server ownership</dt><dd><code>{selected.proposedServerOwnership}</code> — not created by this increment</dd></dl><h3>Prerequisite work packages</h3><div className="greeto-inline-links">{selected.predecessors.length?selected.predecessors.map(id=><button type="button" className="greeto-button" key={id} onClick={()=>{const task=workPackages.find(t=>t.id===id);if(task)showTask(task);}}>{id}</button>):<span>No predecessor IDs listed in the source tracker.</span>}</div><Notice>{selected.scopeNote}</Notice><button className="greeto-button primary" type="button" onClick={()=>onNavigate(selected.frontendFeature)}>Open {getFeature(selected.frontendFeature)?.label||'implementation view'} →</button></>:<p>Select a work package to review its acceptance criteria, dependencies, ownership and source row.</p>}</article>
    </>}
    {view==='features'&&groups.map(group=>{const rows=features.filter(f=>f.group===group.id&&`${f.label} ${f.id} ${f.description}`.toLowerCase().includes(query.toLowerCase()));return rows.length?<section key={group.id} className="greeto-feature-section"><h2>{group.label}</h2><div className="greeto-feature-grid">{rows.map(feature=><article className="greeto-card" key={feature.id}><span className="greeto-badge">{feature.uiStatus==='existing_screen'?'Existing screen':'Frontend configuration'}</span><h3>{feature.label}</h3><p>{feature.description}</p><code>{feature.route}</code><small>{feature.fields.length} parameters · {feature.sourceSection}</small><p className="greeto-muted">{feature.serverStatus==='not_connected'?'Backend integration pending':'Existing API integration not reverified'}</p><button className="greeto-button" type="button" onClick={()=>onNavigate(feature.id)}>Open feature →</button></article>)}</div></section>:null;})}
    {view==='api'&&<div className="greeto-card"><h2>Actual legacy API function signatures</h2><Notice>Extracted from the supplied frontend service. Paths are observed literals, not proof that a live server supports them. Dynamic request construction must be checked in the source.</Notice><div className="greeto-table-wrap"><table><thead><tr><th>Export / parameters</th><th>Observed path literals</th><th>Source</th></tr></thead><tbody>{apiInventory.filter(api=>`${api.name} ${api.parameters}`.toLowerCase().includes(query.toLowerCase())).map(api=><tr key={api.name}><td><code>{api.name}({api.parameters})</code></td><td>{api.endpointLiterals.length?api.endpointLiterals.map((path,i)=><code className="greeto-block" key={i}>{path}</code>):'Dynamic or no path literal captured'}</td><td><code>{api.source}:{api.line}</code></td></tr>)}</tbody></table></div></div>}
  </PageLayout>;
}
