import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {egressView, egressParameters} from '../src/features/implementation/egress-view.mjs';
const scope = {tenantId:'11111111-1111-1111-1111-111111111111',workspaceId:'22222222-2222-2222-2222-222222222222',environmentId:'33333333-3333-3333-3333-333333333333'};
const now = Date.parse('2026-09-08T00:00:01.000Z');
const observation = () => ({scope:{...scope},observedAt:'2026-09-08T00:00:00.000Z',expiresAt:'2026-09-08T00:00:30.000Z',outcome:'accepted_by_endpoint',statusCode:202,bodyComplete:true,responseBytes:12,failureCode:''});
const view = patch => egressView({expectedScope:scope,observation:{...observation(),...patch},now});
test('missing integration is explicit',()=>assert.equal(egressView().state,'not_connected'));
test('fresh acceptance is not business completion',()=>{const r=view({});assert.equal(r.details.statusCode,202);assert.match(r.reason,/no business or ledger completion/);});
for (const field of Object.keys(scope)) test(`wrong ${field} is withheld`,()=>assert.equal(view({scope:{...scope,[field]:'44444444-4444-4444-4444-444444444444'}}).details,null));
for (const patch of [{expiresAt:'2026-09-08T00:00:01.000Z'},{expiresAt:'2026-09-08T00:00:00.000Z'},{observedAt:'2026-09-08T00:00:02.000Z'},{expiresAt:'2026-09-08T00:10:00.000Z'},{expiresAt:'2026-02-30T00:00:00.000Z'},{expiresAt:'invalid'},{statusCode:500},{outcome:'ready'},{responseBytes:-1},{responseBytes:1048578},{failureCode:'secret token'},{bodyComplete:'yes'}]) test(`invalid observation ${JSON.stringify(patch)}`,()=>assert.equal(view(patch).details,null));
test('unknown cannot display acceptance',()=>{const r=view({outcome:'unknown',statusCode:0,bodyComplete:false,responseBytes:0,failureCode:'HTTP_UNAVAILABLE'});assert.equal(r.state,'observed');assert.match(r.reason,/Do not invent success/);});
test('blocked cannot retain stale HTTP facts',()=>assert.equal(view({outcome:'blocked',statusCode:0,failureCode:'EGRESS_DENIED'}).details,null));
test('2xx followed by a capped body retains acceptance',()=>{const r=view({bodyComplete:false,responseBytes:513,failureCode:'RESPONSE_TOO_LARGE'});assert.equal(r.details.outcome,'accepted_by_endpoint');});
test('redirect remains not accepted',()=>assert.equal(view({outcome:'not_accepted',statusCode:302}).details.statusCode,302));
test('untrusted extra response fields never leak',()=>{const r=view({url:'secret-url',body:'private',token:'private',headers:{Authorization:'private'}});assert.ok(!JSON.stringify(r).includes('private'));});
test('host parameter table is read-only documentation',()=>{assert.equal(egressParameters.length,8);assert.ok(egressParameters.every(p=>p.length===3));});
test('panel uses existing components and has no active network controls',()=>{const s=readFileSync(new URL('../src/features/implementation/EgressBoundaryPanel.jsx',import.meta.url),'utf8');assert.match(s,/shared\/ui\/PageLayout/);assert.match(s,/disabled aria-describedby/);assert.doesNotMatch(s,/fetch\(|axios|localStorage|dangerouslySetInnerHTML|<input/);});
test('existing Implementation Center mounts the egress panel',()=>{const s=readFileSync(new URL('../src/features/implementation/ImplementationCenter.jsx',import.meta.url),'utf8');assert.match(s,/<ProductionReadinessPanel\/><TenantScopePanel\/><OutboxStatusPanel\/><EgressBoundaryPanel\/>/);});
